resources:
  db:
    config:
      connection_path: '../data/protodb.db'
  s3:
    config:
      path: '../data'
ops:
  page_list:
    config:
      fetch_pages: 10
      start_url: "https://www.cian.ru/cat.php?"
      params:
        deal_type: 'sale'
        demolished_in_moscow_programm: '0'
        engine_version: '2'
        object_type%5B0%5D: '1'
        offer_type: 'flat'
        region: '1'
        p: '1'
        room1: '1'
        sort: 'creation_date_desc'
        wp: '1'