resources:
  db_resource:
    config:
      connection: '../data/protodb.db'
  s3_resource:
    config:
      auth: 'some_login'
ops:
  model_update:
    config:
      fetch_pages: 3
      start_url: "https://www.cian.ru/cat.php?"